[package]
name = "ligen-editor"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
documentation.workspace = true
readme.workspace = true

[dependencies]
gui-runtime.workspace = true
ligen-ir.workspace    = true
serde.workspace       = true