[package]
name = "ligen-ir"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ligen-utils  = { path = "../utils" }
serde        = { version = "1.0.131", features = [ "derive" ] }

[dev-dependencies]
pretty_assertions = "0.7.2"
