[workspace]
members = [
    "ligen",
#    "generators/ligen-c",
#    "generators/ligen-cmake",
    "generators/ligen-csharp",
    "examples/example"
#    "ligen-cpp/crates/core",
#    "ligen-cpp/crates/macro",
#    "ligen-cpp/crates/main",
#    "ligen-cpp/examples/cpp-example",
#    "ligen-csharp/crates/core",
#    "ligen-csharp/crates/macro",
#    "ligen-csharp/crates/main",
#    "ligen-csharp/examples/csharp-example",
]
