[workspace]
members = [
    "ligen",
    "ligen/ir",
    "ligen/utils",
    "ligen/traits",
    "generators/ligen-cargo",
    "generators/ligen-rust",
    "generators/ligen-cmake",
    "generators/ligen-c",
#    "generators/ligen-csharp",
#    "examples/example",
#    "generators/ligen-csharp/tests/rust"
]
