[workspace]
members = [
    "ligen",
    "ligen/ir",
    "ligen/utils",
    "ligen/traits",
#    "generators/ligen-c",
#    "generators/ligen-cmake",
#    "generators/ligen-csharp",
#    "generators/ligen-cargo",
#    "generators/ligen-rust",
#    "examples/example",
#    "generators/ligen-csharp/tests/rust"
#    "ligen-cpp/crates/core",
#    "ligen-cpp/crates/macro",
#    "ligen-cpp/crates/main",
#    "ligen-cpp/examples/cpp-example",
#    "ligen-csharp/crates/core",
#    "ligen-csharp/crates/macro",
#    "ligen-csharp/crates/main",
#    "ligen-csharp/examples/csharp-example",
]
