[workspace]
members = ["core", "macro"]

[patch.crates-io]
ligen-core = { git = "https://github.com/sensorial-systems/ligen/", branch = "main" }

[patch."https://github.com/sensorial-systems/ligen/"]
ligen-core = { path = "./core" }