[package]
name        = "ligen-core"
version     = "0.1.2"
authors     = ["Danilo Guanabara <danguafer@gmail.com>"]
edition     = "2018"
description = "Language Interface Generator Core"
license     = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.24"
syn          = { version = "1.0.53", features = [ "full" ] }
quote       = "1.0.7"
libloading  = "0.6.6"
derive_more = "0.99.11"
