[workspace]
members = [
    "ligen",
    "ligen-c",
    "ligen-cmake",
#    "ligen-cpp/crates/core",
#    "ligen-cpp/crates/macro",
#    "ligen-cpp/crates/main",
#    "ligen-cpp/examples/cpp-counter",
#    "ligen-csharp/crates/core",
#    "ligen-csharp/crates/macro",
#    "ligen-csharp/crates/main",
#    "ligen-csharp/examples/csharp-counter",
]