[workspace]
members = [
    "ligen",
    "ligen/common",
    "ligen/ir",
    "ligen/parsing",
    "ligen/utils",
    "ligen/traits",
    "runtime/ligen-rust-runtime",
    "generators/ligen-cargo",
    "generators/ligen-rust",
    "generators/ligen-cmake",
    "generators/ligen-c",
    "generators/ligen-csharp",
    "examples/example"
]
