[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name              = "ligen-cmake"
version           = "0.1.4"
description       = "CMake library generator"
documentation     = "https://docs.rs/ligen-cmake"
readme            = "README.md"

[dependencies]
ligen.workspace = true
