[package]
name    = "ligen"
version = "0.1.0"
authors = ["Danilo Guanabara Fernandes"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.24"
ligen-core  = { path = "../core" }
