[package]
name = "ligen-macro"
version.workspace       = true
authors.workspace       = true
edition.workspace       = true
description.workspace   = true
license.workspace       = true
documentation.workspace = true
readme.workspace        = true

[lib]
proc-macro = true

[dependencies]
