[package]
name    = "counter"
version = "0.1.0"
authors = ["Danilo Guanabara <danilo@sensorial.systems>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib","staticlib"]

[build-dependencies]
syn         = "1.0.74"
ligen       = { path = "../../../ligen" }
ligen-c     = { path = "../.." }
ligen-cmake = { path = "../../../ligen-cmake" }
