[workspace]

[package]
name = "ffi_{name}"
version = "{version}"
edition = "2018"

[lib]
crate-type = ["staticlib", "dylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# FIXME: Hardcoded path.
ligen = {{ path = "../../../../../../../ligen/ligen" }}
{name} = {{ path = "{path}" }}
