[package]
name = "ligen-wgsl-generator"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
documentation.workspace = true
readme.workspace = true

[dependencies]
ligen-transformer.workspace = true
ligen-idl.workspace = true
ligen-ir.workspace = true