[package]
name = "ligen-rust-generator"
version.workspace = true
edition.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
documentation.workspace = true
readme.workspace = true

[dependencies]
ligen-transformer.workspace = true
syn.workspace = true
ligen-ir.workspace = true
proc-macro2.workspace = true
anyhow.workspace = true