[package]
name          = "ligen-cpp"
version       = "0.1.0"
authors       = ["Danilo Guanabara <danilo@sensorial.systems>"]
edition       = "2018"
description   = "Language interface generator"
documentation = "https://docs.rs/ligen-cpp"
readme        = "../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ligen-cpp-macro = { path = "../macro" }
ligen-cpp-core  = { path = "../core"  }
