[package]
name = "ligen-rust-parser"
version = "0.1.0"
edition.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
documentation.workspace = true
readme.workspace = true

[dependencies]
ligen.workspace = true
syn.workspace = true
cargo_toml.workspace = true
proc-macro2.workspace = true
quote.workspace = true
anyhow.workspace = true

[dev-dependencies]
ligen-ir = { workspace = true, features = ["mocks"]}
project-root.workspace = true