[package]
name          = "ligen"
version       = "0.1.17-alpha.0"
authors       = ["Danilo Guanabara <danguafer@gmail.com>"]
edition       = "2018"
description   = "Language Interface Generator Core"
license       = "Apache-2.0"
documentation = "https://docs.rs/ligen-core"
readme        = "../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn          = { version = "1.0.73", features = [ "full" ] }
serde_json   = "1.0.64"
cargo_toml   = "0.10.0"
serde        = { version = "1.0.126", features = [ "derive" ] }
ligen-macro  = { path = "macro" }
ligen-ir     = { path = "ir" }
ligen-utils  = { path = "utils" }
ligen-traits = { path = "traits" }
proc-macro2  = "1.0.26"
libloading   = "0.7.0"
derive_more  = "0.99.16"
backtrace    = "0.3.61"
lazy_static  = "1.4.0"

[dev-dependencies]
pretty_assertions = "0.7.2"
ligen-cargo = { path = "../generators/ligen-cargo" }