[package]
name    = "example"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
bindings = [
    "ligen",
    "ligen-rust-parser",
]

[lib]
crate-type = ["lib", "staticlib"]

[dependencies]
ligen-macro.workspace = true

[build-dependencies]
ligen               = { workspace = true, optional = true }
ligen-rust-parser   = { workspace = true, optional = true }
