[package]
name          = "ligen-csharp"
version       = "0.1.0"
authors       = ["Danilo Guanabara <danguafer@gmail.com>"]
edition       = "2018"
description   = "Language interface generator"
documentation = "https://docs.rs/ligen-csharp"
readme        = "../../README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ligen-csharp-macro = { path = "../macro" }
ligen-csharp-core  = { path = "../core"  }
