name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests
        run: cargo test --verbose
  nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install latest nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - name: Tests
      run: cargo test --verbose
