name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest] # ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: All targets checks
        run: cargo check --workspace --all-targets
      - name: All features checks
        run: cargo check --workspace --all-features --lib --target wasm32-unknown-unknown
      - name: Rust Format checks
        run: cargo fmt --all -- --check
      - name: Clippy checks
        run: cargo clippy --workspace --all-targets --all-features --  -D warnings -W clippy::all
      - name: Documentation tests
        run: cargo test --workspace --doc
      - name: All features for all targets tests
        run: cargo test --workspace --all-targets --all-features
      - name: Web build test
        run: trunk build
