on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Release
    name: Release
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: sensorial-systems/cargo-release-action@main
        with:
          major-label: major
          minor-label: minor
          patch-label: patch
          cargo-token: ${{ secrets.CARGO_TOKEN }}
